product/urls.py
from django.contrib import admin
from django.urls import path, include
from product.views import (
    Homepage,
    Homeproducts,
    Detailsproduct,
    Pesquisaproduct,
    Paginaperfil,
    Criarconta,
)
from django.contrib.auth import views as auth_view

app_name = "product"

urlpatterns = [
    path("", Homepage.as_view(), name="homepage"),
    path("product/", Homeproducts.as_view(), name="homeproducts"),
    path("product/<int:pk>", Detailsproduct.as_view(), name="detailsproduct"),
    path("pesquisa/", Pesquisaproduct.as_view(), name="pesquisaproduct"),
    path("login/", auth_view.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("editarperfil/<int:pk>", Paginaperfil.as_view(), name="editarperfil"),
    path("criarconta/", Criarconta.as_view(), name="criarconta"),
]

trabalho_aoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import frontpage, shop
from product.views import product
from product.views import product2
from product.views import product3
from product.views import product4

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("shop/", shop, name="shop"),
    path("product/product/", product, name="product"),
    path("product/product2/", product2, name="product2"),
    path("product/product3/", product3, name="product3"),
    path("product/product4/", product4, name="product4"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

product/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import AbstractUser


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    def __str__(self):
        return self.name


class Product(models.Model):
    categoria = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    titulo = models.CharField(max_length=255)
    thumb = models.ImageField(upload_to="thumb_products")
    slug = models.SlugField()
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo


class Episodio(models.Model):
    product = models.ForeignKey(
        "Product", related_name="episodios", on_delete=models.CASCADE
    )
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField()
    price = models.IntegerField()
    quantidade = models.IntegerField()
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.product.titulo + " - " + self.titulo


class Usuario(AbstractUser):
    products_vistos = models.ManyToManyField("Product")

product/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)


class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ("username", "email", "password1", "password2")

core/views.py
from django.shortcuts import render

from product.models import Product

def frontpage(request):
        products = Product.objects.all()[0:8]

        return render(request, 'core/frontpage.html', {'products': products})

def shop(request):
        products = Product.objects.all()

        return render(request, 'core/shop.html', {'products': products})

product/views.py
from django.shortcuts import render, redirect, reverse
from .models import Product, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    FormView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin


# criar views:
class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("product:homeproducts")
        else:
            return super().get(self, request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse("product:login")
        else:
            return reverse("product:criarconta")


class Homeproducts(LoginRequiredMixin, ListView):
    template_name = "homeproducts.html"
    model = Product


class Detailsproduct(LoginRequiredMixin, DetailView):
    template_name = "detalhesproduct.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super(Detailsproduct, self).get_context_data(**kwargs)
        products_relacionados = Product.objects.filter(
            categoria=self.get_object().categoria
        )[0:5]
        context["products_relacionados"] = products_relacionados
        return context

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        product.visualizacoes += 1
        product.save()
        usuario = request.user
        usuario.products_vistos.add(product)
        return super().get(self, request, *args, **kwargs)


class Pesquisaproduct(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Product

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get("query")
        if termo_pesquisa:
            object_list = Product.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return None


class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ["first_name", "last_name", "email"]

    def get_success_url(self):
        return reverse("product:homeproducts")


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("product:login")


def product(request):
    return render(request, "product/product.html")


def product2(request):
    return render(request, "product/product2.html")


def product3(request):
    return render(request, "product/product3.html")


def product4(request):
    return render(request, "product/product4.html")

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <body>
        <nav class="border-b border-gray-300">
            <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
                <div class="menu-left flex items-center space-x-6">
                    <a href="#" class="py-4 text-lg text-yellow-500 font-semibold">Papelaria Space</a>

                    <ul class="flex items-center space-x-4">
                        <li><a href="{% url 'shop' %}">Loja</a></li>
                    </ul>
                </div>
        <div class="w-6/12 flex flex-nowrap justify-end">
            <div class="mr-2">
                <a>
                    <button class="bg-yellow-600 text-white py-1 px-3 rounded-md">
                        Editar Perfil
                    </button>
                </a>
            </div>
            <div class="mr-2">
                <a>
                    <button class="bg-yellow-600 text-white py-1 px-3 rounded-mr">
                        SAIR
                    </button>
                </a>
            </div>
        </div>    
        </nav>

        <main>
            {% block content %}
            {% endblock %}
        </main>

        <footer class="bg-gray-100">
            <div class="max-w-6xl mx-auto py-10 px-6 xl:px-0 md:flex justify-between">
                <div class="footer-left mb-12 md:mb-0">
                    <h2 class="mb-1 uppercase text-lg">Sobre o grupo</h2>
                    <p class="text-gray-700">João Victor Michels Behn</p>
                    <p class="text-gray-700">Leonardo da Rosa Pereira</p>
                    <p class="text-gray-700">Mauro Sérgio J A Pereira</p>
                    <p class="text-gray-700">Natalia Geni Felipe Spektor</p>
                </div>

                <div class="footer-right">
                    <h2 class="mb-5 uppercase text-lg">Link do Github</h2>

                    <ul class="space-y-2">
                        <li><a href="#" class="text-purple-500 hover:text-purple-800">Github do leo</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

product/templates/detalhesproduct.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomePage Papelaria
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ object.thumb.url }}'); background-size: cover;">
            <div>
                <h2 class="text-6xl font-semibold text-black my-4">
                    {{ object.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-black my-4">
                    {{ object.descricao|slice:":100" }}...
                </p>
                
            </div>
        </section> 
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-black text-3xl font-medium">
                    Categoria: {{ object.categoria }}
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-black text-lg">
                        Visualizações: {{ object.visualizacoes }}
                    </p>
                </div>

                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="bg-white py-1 px-3 text-black md:text-lg rounded-md">
                        Variedade:
                    <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0">
                    <div class="products flex items-center flex-wrap">
                        <div class="w-full md:w-1/3 xl:w-1/4 p-6">
                            <a href="#">
                                <img class="rounded-xl hover:shadow-lg src=https://m.media-amazon.com/images/I/61qJtbgF-TL.__AC_SX300_SY300_QL70_ML2_.jpg">
                            </a>
                
                            <div class="pt-3 flex items-center justify-between">
                                <a href="#"> {{ object.categoria }} Produto A</a>
                                    
                                    <a href="product/" class="text-yellow-500 hover:text-yellow-800">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                    </svg>
                                </a>
                            </div>
                
                            <p class="pt-1 text-gray-400">R$3,50</p>
                        </div>
                
                        <div class="w-full md:w-1/3 xl:w-1/4 p-6">
                            <a href="#">
                                <img class="rounded-xl hover:shadow-lg">
                            </a>
                
                            <div class="pt-3 flex items-center justify-between">
                                <a href="#"> {{ object.categoria }} Produto B</a>
                
                                <a href="product2/" class="text-yellow-500 hover:text-yellow-800">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                    </svg>
                                </a>
                            </div>
                
                            <p class="pt-1 text-gray-400">R$ 4,20</p>
                        </div>
                        
                        <div class="w-full md:w-1/3 xl:w-1/4 p-6">
                            <a href="#">
                                <img class="rounded-xl hover:shadow-lg">
                            </a>
                
                            <div class="pt-3 flex items-center justify-between">
                                <a href="#"> {{ object.categoria }} Produto C</a>
                
                                <a href="product3/" class="text-yellow-500 hover:text-yellow-800">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                    </svg>
                                </a>
                            </div>
                
                            <p class="pt-1 text-gray-400">R$ 5,30</p>
                        </div>
                
                        <div class="w-full md:w-1/3 xl:w-1/4 p-6">
                            <a href="#">
                                <img class="rounded-xl hover:shadow-lg">
                            </a>
                
                            <div class="pt-3 flex items-center justify-between">
                                <a href="#"> {{ object.categoria }} Produto D</a>
                
                                <a href="product4/" class="text-yellow-500 hover:text-yellow-800">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                    </svg>
                                </a>
                            </div>
                
                            <p class="pt-1 text-gray-400">$6,85</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-black text-2xl font-medium">
                    Relacionados:
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for product in products_relacionados %}
                        <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                            <a href="{% url 'product:detailsproduct' product.pk %}">
                                <img src="{{ product.thumb.url }}" class="object-cover w-full h-full " alt="">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

product/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomePage Papelaria
{% endblock %}

{% block head %}
<style>
    #id_email{
        width: 100%;
        color: #000000;
        padding: 5px 5px;
    }
</style>
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-white bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/v.png' %}'); background-size: cover;">
        <div class="z-10 h-full py-32 md:py-0 text-yellow-500 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Materias de Papelaria, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5 text-black">
                Adquira onde quiser. Cancele quando quiser.
            </h3>
            
            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-gray-300 font-medium md:font-normal flex justify-center items-center py-1 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                <p class="text-gray-700">Acessar</p>
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                    </a>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Divirta-se!
            </h2>
            <h5 class="md:text-xl text-lg">
                Adquira seus materiais de papelaria, grande variedade e boa qualidade.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/b.jpg' %}" class="w-8/12" alt="foto" id='SFSCU' width='50' height='50'>
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/c.jpg' %}" class="w-8/12" alt="foto" id='b' width='50' height='50'>
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Escolha seus materiais preferidos para trabalhar.
            </h2>
            <h5 class="md:text-xl text-lg">
                Marque seus favoritos facilmente.
            </h5>
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Crie perfil para acesso.
            </h2>
            <h5 class="md:text-xl text-lg">
                Permita que você tenham uma variedade de materiais.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/d.png' %}" class="w-8/12" alt="foto" id='q' width='50' height='50'>
        </div>
    </section>
        <footer class="bg-gray-100">
            <div class="max-w-6xl mx-auto py-10 px-6 xl:px-0 md:flex justify-between">
                <div class="footer-left mb-12 md:mb-0">
                    <h2 class="mb-1 uppercase text-gray-700">Sobre o grupo</h2>
                    <p class="text-gray-700">João Victor Michels Behn</p>
                    <p class="text-gray-700">Leonardo da Rosa Pereira</p>
                    <p class="text-gray-700">Mauro Sérgio J A Pereira</p>
                    <p class="text-gray-700">Natália Geni Felipe Spektor</p>
                </div>    
                <div class="footer-right">
                    <h2 class="mb-3 uppercase text-lg text-gray-700">Link dos Github</h2>
                    <ul class="space-y-2">
                        <li><a href="#" class="text-purple-500 hover:text-purple-800">Github do leo</a></li>
                    </ul>
                </div>
            </div>
        </footer>
{% endblock %}

product/templates/homeproducts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomePage Papelaria
{% endblock %}

{% block content %}
<div class="px-6 py-10 lg:py-20 bg-yellow-500">
    <div class="max-w-3xl mx-auto">
        <p class="mb text-3xl lg:text-5xl text-white">Bem Vindo a Papelaria</p>
    </div>
</div>

    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="bg-yellow-500 py-1 px-3 text-white md-4:text-lg rounded-md">
                    Novos Produtos:
                </h2>
                <div class="wrapper">
                    <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                        <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                        {% for product in lista_products_recentes %}
                            {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'product:detailsproduct' product.pk %}">
                                    <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                            <a href="#section2" class="arrow__btn text-6xl">›</a>
                    </section>
                        {% if lista_products_recentes|length > 4 %}
                            <section id="section2" class="flex flex-nowrap items-center justify-center">
                                <a href="#section1" class="arrow__btn text-6xl">‹</a>
                                    {% for product in lista_products_recentes %}
                                        {% if forloop.counter > 4 %}
                                        <div class="item h-64 w-1/4 m-4">
                                            <a href="{% url 'product:detailsproduct' product.pk %}">
                                                <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                            </a>
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                <a href="#section1" class="arrow__btn text-6xl">›</a>
                            </section>
                        {% endif %}    
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="bg-yellow-500 py-1 px-3 text-white md-4:text-lg rounded-md">
                    Produtos em Alta:
                </h2>
                <div class="wrapper">
                    <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                        <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                        {% for product in lista_products_em_alta %}
                            {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'product:detailsproduct' product.pk %}">
                                    <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                            <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                    </section>
                    {% if lista_products_recentes|length > 4 %}
                        <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                            <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                            {% for product in lista_products_em_alta %}
                                {% if forloop.counter > 4 %}
                                <div class="item h-64 w-1/4 m-4">
                                    <a href="{% url 'product:detailsproduct' product.pk %}">
                                        <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    </a>
                                </div>
                                {% endif %}
                            {% endfor %}
                            <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                        </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="bg-yellow-500 py-1 px-3 text-white md-4:text-lg rounded-md">
                    Produtos Vistos:
                </h2>
                <div class="wrapper">
                    <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                        <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
                            {% for product in request.user.products_vistos.all %}
                                {% if forloop.counter < 5 %}
                                <div class="item h-64 w-1/4 m-4">
                                    <a href="{% url 'product:detailsproduct' product.pk %}">
                                        <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    </a>
                                </div>
                                {% endif %}
                            {% endfor %}
                                <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
                    </section>
                        {% if request.user.products_vistos.all|length > 4 %}
                            <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                                <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                                {% for product in request.user.products_vistos.all %}
                                    {% if forloop.counter > 4 %}
                                    <div class="item h-64 w-1/4 m-4">
                                        <a href="{% url 'product:detailsproduct' product.pk %}">
                                            <img src="{{ product.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                        </a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                            </section>
                        {% endif %}
                </div>
            </div>
        </section>
        <footer class=" px-10 py-5 ">
            <ul class="flex justify-between items-center">
                <div class="px-6 py-10 rounded-xl lg:py-10 bg-yellow-500">
                    <div class="max-w-3xl mx-auto text-center">
                        <a href="shop/" class="inline-block px-4 py-2 rounded-xl text-white hover:bg-gray-200">Compre!</a>
                    </div>
                </div>
            </ul>
        </footer>
    </main>
{% endblock %}

product/templates/pesquisa.html
{% extends 'base.html' %}

{% block title %}
Pesquisa de Materiais
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for space in object_list %}
                        <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                            <a href="{% url 'product:detailsproduct' product.pk %}">
                                <img src="{{ product.thumb.url }}" class="object-cover w-full h-full " alt="">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class = "w-2/12" src="{% static 'images/paperpal.jpg' %}">
            <p class="text-black">Papelaria Space</p>
        </a>
    </div>
    
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
            <div class="mr-2">
                <form method="get" action="{% url 'product:pesquisaproduct' %}">
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                    <input type="submit" value="">
                </form>
            </div>
        {% endif %}

        <div class="mr-2">
            {% if user.is_authenticated %}
                <a href="{% url 'product:editarperfil' request.user.pk %}">
                    <button class="bg-blue-600 text-white py-1 px-3 rounded-md">
                        Editar Perfil
                    </button>
                </a>
            {% endif %}
        </div>
        
        <div class="mr-2">
            {% if user.is_authenticated %}
                <a href="{% url 'product:logout' %}">
                    <button class="bg-blue-600 text-white py-1 px-3 rounded-mr">
                        SAIR
                    </button>
                </a>
            {% else %}
                <a href="{% url 'product:login' %}">
                    <button class="bg-blue-600 text-white py-1 px-3 rounded-md">
                        Login
                    </button>
                </a>
            {% endif %}
        </div>
    </div>
</nav>